name: FastAPI Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t demo-fastapi:latest .

    - name: Push Docker image
      run: |
        docker tag demo-fastapi:latest ${{ secrets.DOCKER_USERNAME }}/demo-fastapi:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-fastapi:latest

    # Optional: deploy to remote server
    - name: Deploy via Docker Compose on remote server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/demo-fastapi
          docker-compose pull
          docker-compose up -d --build
