name: FastAPI Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t demo-fastapi:latest .

    - name: Run Docker container
      run: |
        docker run -d --name demo-fastapi-container -p 8000:8000 demo-fastapi:latest

    - name: Test FastAPI container
      run: |
        sleep 5 # wait for the container to start
        curl -f http://localhost:8000/ || echo "FastAPI container test failed"

    - name: Stop and remove container
      if: always()
      run: |
        docker stop demo-fastapi-container
        docker rm demo-fastapi-container
