name: Run Docker Container

on:
  workflow_dispatch:   # allows manual trigger from Actions tab
  push:                # also runs when code is pushed
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      # 3. Run Docker container
      - name: Run Docker container
        run: |
          docker run --name my-app-container -d -p 8080:8080 my-app:latest

      # 4. Check logs (optional)
      - name: Show container logs
        run: docker logs my-app-container
